#ifndef _LINUX_AUTONUMA_TYPES_H
#define _LINUX_AUTONUMA_TYPES_H

#ifdef CONFIG_AUTONUMA

#include <linux/numa.h>

/*
 * Per-mm (per-process) structure that is dynamically allocated if
 * AutoNUMA is possible. It contains the NUMA memory placement
 * statistics generated by the knuma scan daemon. These structures are
 * linked together in a list headed within the knumad_scan
 * structure. See struct knumad_scan for more details.
 */
struct mm_autonuma {
	/* link for knuma_scand's list of mm structures to scan */
	struct list_head mm_node;
	/* Pointer to associated mm structure */
	struct mm_struct *mm;

	/*
	 * Zeroed from here during allocation, check
	 * mm_autonuma_reset() if you alter the below.
	 */

	/* Pass sequence counter for this mm */
	unsigned long mm_numa_fault_pass;
	/* Total number of pages that will trigger NUMA faults for this mm */
	unsigned long mm_numa_fault_tot;
	/* Number of pages that will trigger NUMA faults for each [nid] */
	unsigned long mm_numa_fault[0];
	/* do not add more variables here, the above array size is dynamic */
};

extern int alloc_mm_autonuma(struct mm_struct *mm);
extern void free_mm_autonuma(struct mm_struct *mm);
extern void __init mm_autonuma_init(void);

/*
 * Per-task (thread) structure dynamically allocated if autonuma is
 * possible. It contains the preferred node where the thread should be
 * scheduled and the per-thread NUMA access statistics generated by
 * the NUMA hinting page faults. Note that this structure is only
 * relevant if the task has a valid mm structure (tsk->mm != NULL).
 */
struct task_autonuma {
	/* node id the CPU scheduler should try to stick with (-1 if none) */
	int autonuma_nid;

	/*
	 * Zeroed from here during allocation, check
	 * mm_autonuma_reset() if you alter the below.
	 */

	/* Pass sequence counter for this thread */
	unsigned long task_numa_fault_pass;
	/* Total number of pages that triggered NUMA faults */
	unsigned long task_numa_fault_tot;
	/* Number of pages that triggered NUMA faults for each [nid] */
	unsigned long task_numa_fault[0];
	/* do not add more variables here, the above array size is dynamic */
};

extern int alloc_task_autonuma(struct task_struct *tsk,
			       struct task_struct *orig,
			       int node);
extern void __init task_autonuma_init(void);
extern void free_task_autonuma(struct task_struct *tsk);

#else /* CONFIG_AUTONUMA */

static inline int alloc_mm_autonuma(struct mm_struct *mm)
{
	return 0;
}
static inline void free_mm_autonuma(struct mm_struct *mm) {}
static inline void mm_autonuma_init(void) {}

static inline int alloc_task_autonuma(struct task_struct *tsk,
				      struct task_struct *orig,
				      int node)
{
	return 0;
}
static inline void task_autonuma_init(void) {}
static inline void free_task_autonuma(struct task_struct *tsk) {}

#endif /* CONFIG_AUTONUMA */

#endif /* _LINUX_AUTONUMA_TYPES_H */
