#ifndef _LINUX_AUTONUMA_TYPES_H
#define _LINUX_AUTONUMA_TYPES_H

#ifdef CONFIG_AUTONUMA

#include <linux/numa.h>

/*
 * Per-mm (process) structure dynamically allocated only if autonuma
 * is not impossible. This links the mm to scan into the
 * knuma_scand.mm_head and it contains the NUMA memory placement
 * statistics for the process (generated by knuma_scand).
 */
struct mm_autonuma {
	/* list node to link the "mm" into the knuma_scand.mm_head */
	struct list_head mm_node;
	struct mm_struct *mm;
	unsigned long mm_numa_fault_pass; /* zeroed from here during allocation */
	unsigned long mm_numa_fault_tot;
	unsigned long mm_numa_fault[0];
};

extern int alloc_mm_autonuma(struct mm_struct *mm);
extern void free_mm_autonuma(struct mm_struct *mm);
extern void __init mm_autonuma_init(void);

/*
 * Per-task (thread) structure dynamically allocated only if autonuma
 * is not impossible. This contains the preferred autonuma_node where
 * the userland thread should be scheduled into (only relevant if
 * tsk->mm is not null) and the per-thread NUMA accesses statistics
 * (generated by the NUMA hinting page faults).
 */
struct task_autonuma {
	int autonuma_node;
	/* zeroed from the below field during allocation */
	unsigned long task_numa_fault_pass;
	unsigned long task_numa_fault_tot;
	unsigned long task_numa_fault[0];
};

extern int alloc_task_autonuma(struct task_struct *tsk,
			       struct task_struct *orig,
			       int node);
extern void __init task_autonuma_init(void);
extern void free_task_autonuma(struct task_struct *tsk);

#else /* CONFIG_AUTONUMA */

static inline int alloc_mm_autonuma(struct mm_struct *mm)
{
	return 0;
}
static inline void free_mm_autonuma(struct mm_struct *mm) {}
static inline void mm_autonuma_init(void) {}

static inline int alloc_task_autonuma(struct task_struct *tsk,
				      struct task_struct *orig,
				      int node)
{
	return 0;
}
static inline void task_autonuma_init(void) {}
static inline void free_task_autonuma(struct task_struct *tsk) {}

#endif /* CONFIG_AUTONUMA */

#endif /* _LINUX_AUTONUMA_TYPES_H */
