#ifndef _LINUX_AUTONUMA_TYPES_H
#define _LINUX_AUTONUMA_TYPES_H

#ifdef CONFIG_AUTONUMA

#include <linux/numa.h>
#include <linux/autonuma_list.h>

/*
 * Per-mm (per-process) structure that is dynamically allocated if
 * AutoNUMA is possible. It contains the NUMA memory placement
 * statistics generated by the knuma scan daemon. These structures are
 * linked together in a list headed within the knumad_scan
 * structure. See struct knumad_scan for more details.
 */
struct mm_autonuma {
	/* link for knuma_scand's list of mm structures to scan */
	struct list_head mm_node;
	/* Pointer to associated mm structure */
	struct mm_struct *mm;

	/*
	 * Zeroed from here during allocation, check
	 * mm_autonuma_reset() if you alter the below.
	 */

	/* Pass sequence counter for this mm */
	unsigned long mm_numa_fault_pass;
	/* Total number of pages that will trigger NUMA faults for this mm */
	unsigned long mm_numa_fault_tot;
	/* Number of pages that will trigger NUMA faults for each [nid] */
	unsigned long mm_numa_fault[0];
	/* do not add more variables here, the above array size is dynamic */
};

extern int alloc_mm_autonuma(struct mm_struct *mm);
extern void free_mm_autonuma(struct mm_struct *mm);
extern void __init mm_autonuma_init(void);

/*
 * Per-task (thread) structure dynamically allocated if autonuma is
 * possible. It contains the preferred node where the thread should be
 * scheduled and the per-thread NUMA access statistics generated by
 * the NUMA hinting page faults. Note that this structure is only
 * relevant if the task has a valid mm structure (tsk->mm != NULL).
 */
struct task_autonuma {
	/* node id the CPU scheduler should try to stick with (-1 if none) */
	int autonuma_nid;

	/*
	 * Zeroed from here during allocation, check
	 * mm_autonuma_reset() if you alter the below.
	 */

	/* Pass sequence counter for this thread */
	unsigned long task_numa_fault_pass;
	/* Total number of pages that triggered NUMA faults */
	unsigned long task_numa_fault_tot;
	/* Number of pages that triggered NUMA faults for each [nid] */
	unsigned long task_numa_fault[0];
	/* do not add more variables here, the above array size is dynamic */
};

/*
 * Per page (or per-pageblock) structure dynamically allocated only if
 * autonuma is possible.
 *
 * This structure takes 12 bytes per page for all architectures. There
 * are two constraints to make this work:
 *
 * 1) the build will abort if MAX_NUMNODES is too big according to
 *    the #error check below
 *
 * 2) AutoNUMA will not succeed to insert into the migration queue any
 *    page whose pfn offset value (offset with respect to the first
 *    pfn of the node) is bigger than AUTONUMA_LIST_MAX_PFN_OFFSET
 *    (NOTE: AUTONUMA_LIST_MAX_PFN_OFFSET is still a valid pfn offset
 *    value). This means with huge node sizes and small PAGE_SIZE,
 *    some pages may not be allowed to be migrated.
 */
struct page_autonuma {
	/*
	 * To modify autonuma_last_nid lockless the architecture,
	 * needs SMP atomic granularity < sizeof(long), not all archs
	 * have that, notably some ancient alpha (but none of those
	 * should run in NUMA systems). Archs without that requires
	 * autonuma_last_nid to be a long.
	 */
#if MAX_NUMNODES > 32767
	/*
	 * Verify at build time that int16_t for autonuma_migrate_nid
	 * and autonuma_last_nid won't risk to overflow, max allowed
	 * nid value is (2**15)-1.
	 */
#error "too many nodes"
#endif
	/*
	 * autonuma_migrate_nid is -1 if the page_autonuma structure
	 * is not linked into any
	 * pgdat->autonuma_migrate_head. Otherwise it means the
	 * page_autonuma structure is linked into the
	 * &NODE_DATA(autonuma_migrate_nid)->autonuma_migrate_head[page_nid].
	 * page_nid is the nid that the page (referenced by the
	 * page_autonuma structure) belongs to.
	 */
	int16_t autonuma_migrate_nid;
	/*
	 * autonuma_last_nid records which is the NUMA nid that tried
	 * to access this page at the last NUMA hinting page fault.
	 * If it changed, AutoNUMA will not try to migrate the page to
	 * the nid where the thread is running on and to the contrary,
	 * it will make different threads trashing on the same pages,
	 * converge on the same NUMA node (if possible).
	 */
	int16_t autonuma_last_nid;

	/*
	 * This is the list node that links the page (referenced by
	 * the page_autonuma structure) in the
	 * &NODE_DATA(dst_nid)->autonuma_migrate_head[page_nid] lru.
	 */
	struct autonuma_list_head autonuma_migrate_node;
};

extern int alloc_task_autonuma(struct task_struct *tsk,
			       struct task_struct *orig,
			       int node);
extern void __init task_autonuma_init(void);
extern void free_task_autonuma(struct task_struct *tsk);

#else /* CONFIG_AUTONUMA */

static inline int alloc_mm_autonuma(struct mm_struct *mm)
{
	return 0;
}
static inline void free_mm_autonuma(struct mm_struct *mm) {}
static inline void mm_autonuma_init(void) {}

static inline int alloc_task_autonuma(struct task_struct *tsk,
				      struct task_struct *orig,
				      int node)
{
	return 0;
}
static inline void task_autonuma_init(void) {}
static inline void free_task_autonuma(struct task_struct *tsk) {}

#endif /* CONFIG_AUTONUMA */

#endif /* _LINUX_AUTONUMA_TYPES_H */
